//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 05:47:04 PM UYT 
//


package dto.migrate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Identificacion de la Empresa
 * 
 * <p>Java class for EncabezadoEnvioType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncabezadoEnvioType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmpCodigo" type="{http://www.invoicy.com.uy/}EmpCodigoType"/>
 *         &lt;element name="EmpPK" type="{http://www.invoicy.com.uy/}EmpPK"/>
 *         &lt;element name="EmpCK" type="{http://www.invoicy.com.uy/}EmpCK"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncabezadoEnvioType", propOrder = {
    "empCodigo",
    "empPK",
    "empCK"
})
public class EncabezadoEnvioType {

    @XmlElement(name = "EmpCodigo", required = true)
    protected String empCodigo;
    @XmlElement(name = "EmpPK", required = true)
    protected String empPK;
    @XmlElement(name = "EmpCK", required = true)
    protected String empCK;

    /**
     * Gets the value of the empCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpCodigo() {
        return empCodigo;
    }

    /**
     * Sets the value of the empCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpCodigo(String value) {
        this.empCodigo = value;
    }

    /**
     * Gets the value of the empPK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpPK() {
        return empPK;
    }

    /**
     * Sets the value of the empPK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpPK(String value) {
        this.empPK = value;
    }

    /**
     * Gets the value of the empCK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpCK() {
        return empCK;
    }

    /**
     * Sets the value of the empCK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpCK(String value) {
        this.empCK = value;
    }

}
