//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 05:47:04 PM UYT 
//


package dto.migrate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Identificacion de la Empresa
 * 
 * <p>Java class for EncabezadoRetornoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncabezadoRetornoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmpCodigo" type="{http://www.invoicy.com.uy/}EmpCodigoType"/>
 *         &lt;element name="MsgCod" type="{http://www.invoicy.com.uy/}MsgCodType" minOccurs="0"/>
 *         &lt;element name="MsgDsc" type="{http://www.invoicy.com.uy/}MsgDscType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncabezadoRetornoType", propOrder = {
    "empCodigo",
    "msgCod",
    "msgDsc"
})
public class EncabezadoRetornoType {

    @XmlElement(name = "EmpCodigo", required = true)
    protected String empCodigo;
    @XmlElement(name = "MsgCod")
    protected Integer msgCod;
    @XmlElement(name = "MsgDsc")
    protected String msgDsc;

    /**
     * Gets the value of the empCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpCodigo() {
        return empCodigo;
    }

    /**
     * Sets the value of the empCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpCodigo(String value) {
        this.empCodigo = value;
    }

    /**
     * Gets the value of the msgCod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMsgCod() {
        return msgCod;
    }

    /**
     * Sets the value of the msgCod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMsgCod(Integer value) {
        this.msgCod = value;
    }

    /**
     * Gets the value of the msgDsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgDsc() {
        return msgDsc;
    }

    /**
     * Sets the value of the msgDsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgDsc(String value) {
        this.msgDsc = value;
    }

}
