//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 05:47:04 PM UYT 
//


package dto.migrate;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Lista de CFEs Retornados
 * 
 * <p>Java class for ListaCFERetornoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListaCFERetornoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CFE" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CFETipo" type="{http://www.invoicy.com.uy/}CFEType"/>
 *                   &lt;element name="CFESerie" type="{http://www.invoicy.com.uy/}SerieType"/>
 *                   &lt;element name="CFENro" type="{http://www.invoicy.com.uy/}NroCFEType"/>
 *                   &lt;element name="CFEStatus" type="{http://www.invoicy.com.uy/}StatusCFE" minOccurs="0"/>
 *                   &lt;element name="CFEEstadoAcuse" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="6"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CFEMsgCod" type="{http://www.invoicy.com.uy/}MsgCodType" minOccurs="0"/>
 *                   &lt;element name="CFEMsgDsc" type="{http://www.invoicy.com.uy/}MsgDscType" minOccurs="0"/>
 *                   &lt;element name="CFEXMLEE" type="{http://www.invoicy.com.uy/}Base64" minOccurs="0"/>
 *                   &lt;element name="CFERepImpressa" type="{http://www.invoicy.com.uy/}Base64" minOccurs="0"/>
 *                   &lt;element name="CFEQrCode" type="{http://www.invoicy.com.uy/}Base64" minOccurs="0"/>
 *                   &lt;element name="CFEFechaHoraConsulta" type="{http://www.invoicy.com.uy/}FechaHoraType" minOccurs="0"/>
 *                   &lt;element name="CFENumReferencia" type="{http://www.invoicy.com.uy/}NumReferencia" minOccurs="0"/>
 *                   &lt;element name="CFECodigoSeguridad" type="{http://www.invoicy.com.uy/}CodigoSeguridad" minOccurs="0"/>
 *                   &lt;element name="CFEDatosAvanzados" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CFEHASH" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="28"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CFEFchHorFirma" type="{http://www.invoicy.com.uy/}FechaHoraType" minOccurs="0"/>
 *                             &lt;element name="CFECAEId" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="99999999999"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CFECAENroIni" type="{http://www.invoicy.com.uy/}NroCFEType" minOccurs="0"/>
 *                             &lt;element name="CFECAENroFin" type="{http://www.invoicy.com.uy/}NroCFEType" minOccurs="0"/>
 *                             &lt;element name="CFECAEFchVenc" type="{http://www.invoicy.com.uy/}FechaType" minOccurs="0"/>
 *                             &lt;element name="CFERUTEmisor" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="12"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CFETotMntPagar" type="{http://www.invoicy.com.uy/}Monto_admite_negType" minOccurs="0"/>
 *                             &lt;element name="NumResAutorizadora" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                   &lt;totalDigits value="4"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="AnoResAutorizadora" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                   &lt;totalDigits value="4"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DireccionInvoiCyWeb" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="120"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CodBarRedPagPrimera" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="30"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CodBarRedPagSegunda" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="30"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CodBarAbtPrimera" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="30"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CodBarAbtSegunda" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="30"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Erros" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ErrosItem" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CFEErrCod" type="{http://www.invoicy.com.uy/}MsgCodType"/>
 *                                       &lt;element name="CFEErrDesc" type="{http://www.invoicy.com.uy/}MsgDscType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ErrosDGI" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ErrosDGIItem" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CFERetCod">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="3"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="CFERetDesc" type="{http://www.invoicy.com.uy/}MsgDscType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListaCFERetornoType", propOrder = {
    "cfe"
})
public class ListaCFERetornoType {

    @XmlElement(name = "CFE", required = true)
    protected List<CFE> cfe;

    /**
     * Gets the value of the cfe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cfe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCFE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CFE }
     * 
     * 
     */
    public List<CFE> getCFE() {
        if (cfe == null) {
            cfe = new ArrayList<CFE>();
        }
        return this.cfe;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CFETipo" type="{http://www.invoicy.com.uy/}CFEType"/>
     *         &lt;element name="CFESerie" type="{http://www.invoicy.com.uy/}SerieType"/>
     *         &lt;element name="CFENro" type="{http://www.invoicy.com.uy/}NroCFEType"/>
     *         &lt;element name="CFEStatus" type="{http://www.invoicy.com.uy/}StatusCFE" minOccurs="0"/>
     *         &lt;element name="CFEEstadoAcuse" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *               &lt;enumeration value="4"/>
     *               &lt;enumeration value="5"/>
     *               &lt;enumeration value="6"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CFEMsgCod" type="{http://www.invoicy.com.uy/}MsgCodType" minOccurs="0"/>
     *         &lt;element name="CFEMsgDsc" type="{http://www.invoicy.com.uy/}MsgDscType" minOccurs="0"/>
     *         &lt;element name="CFEXMLEE" type="{http://www.invoicy.com.uy/}Base64" minOccurs="0"/>
     *         &lt;element name="CFERepImpressa" type="{http://www.invoicy.com.uy/}Base64" minOccurs="0"/>
     *         &lt;element name="CFEQrCode" type="{http://www.invoicy.com.uy/}Base64" minOccurs="0"/>
     *         &lt;element name="CFEFechaHoraConsulta" type="{http://www.invoicy.com.uy/}FechaHoraType" minOccurs="0"/>
     *         &lt;element name="CFENumReferencia" type="{http://www.invoicy.com.uy/}NumReferencia" minOccurs="0"/>
     *         &lt;element name="CFECodigoSeguridad" type="{http://www.invoicy.com.uy/}CodigoSeguridad" minOccurs="0"/>
     *         &lt;element name="CFEDatosAvanzados" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CFEHASH" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="28"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CFEFchHorFirma" type="{http://www.invoicy.com.uy/}FechaHoraType" minOccurs="0"/>
     *                   &lt;element name="CFECAEId" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="99999999999"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CFECAENroIni" type="{http://www.invoicy.com.uy/}NroCFEType" minOccurs="0"/>
     *                   &lt;element name="CFECAENroFin" type="{http://www.invoicy.com.uy/}NroCFEType" minOccurs="0"/>
     *                   &lt;element name="CFECAEFchVenc" type="{http://www.invoicy.com.uy/}FechaType" minOccurs="0"/>
     *                   &lt;element name="CFERUTEmisor" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="12"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CFETotMntPagar" type="{http://www.invoicy.com.uy/}Monto_admite_negType" minOccurs="0"/>
     *                   &lt;element name="NumResAutorizadora" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                         &lt;totalDigits value="4"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="AnoResAutorizadora" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                         &lt;totalDigits value="4"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DireccionInvoiCyWeb" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="120"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CodBarRedPagPrimera" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="30"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CodBarRedPagSegunda" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="30"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CodBarAbtPrimera" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="30"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CodBarAbtSegunda" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="30"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Erros" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ErrosItem" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CFEErrCod" type="{http://www.invoicy.com.uy/}MsgCodType"/>
     *                             &lt;element name="CFEErrDesc" type="{http://www.invoicy.com.uy/}MsgDscType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ErrosDGI" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ErrosDGIItem" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CFERetCod">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="3"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="CFERetDesc" type="{http://www.invoicy.com.uy/}MsgDscType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cfeTipo",
        "cfeSerie",
        "cfeNro",
        "cfeStatus",
        "cfeEstadoAcuse",
        "cfeMsgCod",
        "cfeMsgDsc",
        "cfexmlee",
        "cfeRepImpressa",
        "cfeQrCode",
        "cfeFechaHoraConsulta",
        "cfeNumReferencia",
        "cfeCodigoSeguridad",
        "cfeDatosAvanzados",
        "erros",
        "errosDGI"
    })
    public static class CFE {

        @XmlElement(name = "CFETipo", required = true)
        protected BigInteger cfeTipo;
        @XmlElement(name = "CFESerie", required = true)
        protected String cfeSerie;
        @XmlElement(name = "CFENro", required = true)
        protected BigInteger cfeNro;
        @XmlElement(name = "CFEStatus")
        protected BigInteger cfeStatus;
        @XmlElement(name = "CFEEstadoAcuse")
        protected BigInteger cfeEstadoAcuse;
        @XmlElement(name = "CFEMsgCod")
        protected Integer cfeMsgCod;
        @XmlElement(name = "CFEMsgDsc")
        protected String cfeMsgDsc;
        @XmlElement(name = "CFEXMLEE")
        protected String cfexmlee;
        @XmlElement(name = "CFERepImpressa")
        protected String cfeRepImpressa;
        @XmlElement(name = "CFEQrCode")     
        protected String cfeQrCode;
        //protected byte[] cfeQrCode;
        @XmlElement(name = "CFEFechaHoraConsulta")
        protected XMLGregorianCalendar cfeFechaHoraConsulta;
        @XmlElement(name = "CFENumReferencia")
        protected BigInteger cfeNumReferencia;
        @XmlElement(name = "CFECodigoSeguridad")
        protected String cfeCodigoSeguridad;
        @XmlElement(name = "CFEDatosAvanzados")
        protected CFEDatosAvanzados cfeDatosAvanzados;
        @XmlElement(name = "Erros")
        protected Erros erros;
        @XmlElement(name = "ErrosDGI")
        protected ErrosDGI errosDGI;

        /**
         * Gets the value of the cfeTipo property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCFETipo() {
            return cfeTipo;
        }

        /**
         * Sets the value of the cfeTipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCFETipo(BigInteger value) {
            this.cfeTipo = value;
        }

        /**
         * Gets the value of the cfeSerie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCFESerie() {
            return cfeSerie;
        }

        /**
         * Sets the value of the cfeSerie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCFESerie(String value) {
            this.cfeSerie = value;
        }

        /**
         * Gets the value of the cfeNro property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCFENro() {
            return cfeNro;
        }

        /**
         * Sets the value of the cfeNro property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCFENro(BigInteger value) {
            this.cfeNro = value;
        }

        /**
         * Gets the value of the cfeStatus property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCFEStatus() {
            return cfeStatus;
        }

        /**
         * Sets the value of the cfeStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCFEStatus(BigInteger value) {
            this.cfeStatus = value;
        }

        /**
         * Gets the value of the cfeEstadoAcuse property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCFEEstadoAcuse() {
            return cfeEstadoAcuse;
        }

        /**
         * Sets the value of the cfeEstadoAcuse property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCFEEstadoAcuse(BigInteger value) {
            this.cfeEstadoAcuse = value;
        }

        /**
         * Gets the value of the cfeMsgCod property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCFEMsgCod() {
            return cfeMsgCod;
        }

        /**
         * Sets the value of the cfeMsgCod property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCFEMsgCod(Integer value) {
            this.cfeMsgCod = value;
        }

        /**
         * Gets the value of the cfeMsgDsc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCFEMsgDsc() {
            return cfeMsgDsc;
        }

        /**
         * Sets the value of the cfeMsgDsc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCFEMsgDsc(String value) {
            this.cfeMsgDsc = value;
        }

        /**
         * Gets the value of the cfexmlee property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCFEXMLEE() {
            return cfexmlee;
        }

        /**
         * Sets the value of the cfexmlee property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCFEXMLEE(String value) {
            this.cfexmlee = value;
        }

        /**
         * Gets the value of the cfeRepImpressa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCFERepImpressa() {
            return cfeRepImpressa;
        }

        /**
         * Sets the value of the cfeRepImpressa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCFERepImpressa(String value) {
            this.cfeRepImpressa = value;
        }

        /**
         * Gets the value of the cfeQrCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCFEQrCode() {
            return cfeQrCode;
        }

        /**
         * Sets the value of the cfeQrCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCFEQrCode(String value) {
            this.cfeQrCode = value;
        }

        /**
         * Gets the value of the cfeFechaHoraConsulta property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCFEFechaHoraConsulta() {
            return cfeFechaHoraConsulta;
        }

        /**
         * Sets the value of the cfeFechaHoraConsulta property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCFEFechaHoraConsulta(XMLGregorianCalendar value) {
            this.cfeFechaHoraConsulta = value;
        }

        /**
         * Gets the value of the cfeNumReferencia property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCFENumReferencia() {
            return cfeNumReferencia;
        }

        /**
         * Sets the value of the cfeNumReferencia property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCFENumReferencia(BigInteger value) {
            this.cfeNumReferencia = value;
        }

        /**
         * Gets the value of the cfeCodigoSeguridad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCFECodigoSeguridad() {
            return cfeCodigoSeguridad;
        }

        /**
         * Sets the value of the cfeCodigoSeguridad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCFECodigoSeguridad(String value) {
            this.cfeCodigoSeguridad = value;
        }

        /**
         * Gets the value of the cfeDatosAvanzados property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDatosAvanzados }
         *     
         */
        public CFEDatosAvanzados getCFEDatosAvanzados() {
            return cfeDatosAvanzados;
        }

        /**
         * Sets the value of the cfeDatosAvanzados property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDatosAvanzados }
         *     
         */
        public void setCFEDatosAvanzados(CFEDatosAvanzados value) {
            this.cfeDatosAvanzados = value;
        }

        /**
         * Gets the value of the erros property.
         * 
         * @return
         *     possible object is
         *     {@link Erros }
         *     
         */
        public Erros getErros() {
            return erros;
        }

        /**
         * Sets the value of the erros property.
         * 
         * @param value
         *     allowed object is
         *     {@link Erros }
         *     
         */
        public void setErros(Erros value) {
            this.erros = value;
        }

        /**
         * Gets the value of the errosDGI property.
         * 
         * @return
         *     possible object is
         *     {@link ErrosDGI }
         *     
         */
        public ErrosDGI getErrosDGI() {
            return errosDGI;
        }

        /**
         * Sets the value of the errosDGI property.
         * 
         * @param value
         *     allowed object is
         *     {@link ErrosDGI }
         *     
         */
        public void setErrosDGI(ErrosDGI value) {
            this.errosDGI = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CFEHASH" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="28"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CFEFchHorFirma" type="{http://www.invoicy.com.uy/}FechaHoraType" minOccurs="0"/>
         *         &lt;element name="CFECAEId" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="99999999999"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CFECAENroIni" type="{http://www.invoicy.com.uy/}NroCFEType" minOccurs="0"/>
         *         &lt;element name="CFECAENroFin" type="{http://www.invoicy.com.uy/}NroCFEType" minOccurs="0"/>
         *         &lt;element name="CFECAEFchVenc" type="{http://www.invoicy.com.uy/}FechaType" minOccurs="0"/>
         *         &lt;element name="CFERUTEmisor" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="12"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CFETotMntPagar" type="{http://www.invoicy.com.uy/}Monto_admite_negType" minOccurs="0"/>
         *         &lt;element name="NumResAutorizadora" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;totalDigits value="4"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="AnoResAutorizadora" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;totalDigits value="4"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DireccionInvoiCyWeb" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="120"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CodBarRedPagPrimera" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="30"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CodBarRedPagSegunda" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="30"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CodBarAbtPrimera" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="30"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CodBarAbtSegunda" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="30"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cfehash",
            "cfeFchHorFirma",
            "cfecaeId",
            "cfecaeNroIni",
            "cfecaeNroFin",
            "cfecaeFchVenc",
            "cferutEmisor",
            "cfeTotMntPagar",
            "numResAutorizadora",
            "anoResAutorizadora",
            "direccionInvoiCyWeb",
            "codBarRedPagPrimera",
            "codBarRedPagSegunda",
            "codBarAbtPrimera",
            "codBarAbtSegunda"
        })
        public static class CFEDatosAvanzados {

            @XmlElement(name = "CFEHASH")
            protected String cfehash;
            @XmlElement(name = "CFEFchHorFirma")
            protected XMLGregorianCalendar cfeFchHorFirma;
            @XmlElement(name = "CFECAEId")
            protected Long cfecaeId;
            @XmlElement(name = "CFECAENroIni")
            protected BigInteger cfecaeNroIni;
            @XmlElement(name = "CFECAENroFin")
            protected BigInteger cfecaeNroFin;
            @XmlElement(name = "CFECAEFchVenc")
            protected XMLGregorianCalendar cfecaeFchVenc;
            @XmlElement(name = "CFERUTEmisor")
            protected String cferutEmisor;
            @XmlElement(name = "CFETotMntPagar")
            protected BigDecimal cfeTotMntPagar;
            @XmlElement(name = "NumResAutorizadora")
            protected BigInteger numResAutorizadora;
            @XmlElement(name = "AnoResAutorizadora")
            protected BigInteger anoResAutorizadora;
            @XmlElement(name = "DireccionInvoiCyWeb")
            protected String direccionInvoiCyWeb;
            @XmlElement(name = "CodBarRedPagPrimera")
            protected String codBarRedPagPrimera;
            @XmlElement(name = "CodBarRedPagSegunda")
            protected String codBarRedPagSegunda;
            @XmlElement(name = "CodBarAbtPrimera")
            protected String codBarAbtPrimera;
            @XmlElement(name = "CodBarAbtSegunda")
            protected String codBarAbtSegunda;

            /**
             * Gets the value of the cfehash property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCFEHASH() {
                return cfehash;
            }

            /**
             * Sets the value of the cfehash property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCFEHASH(String value) {
                this.cfehash = value;
            }

            /**
             * Gets the value of the cfeFchHorFirma property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCFEFchHorFirma() {
                return cfeFchHorFirma;
            }

            /**
             * Sets the value of the cfeFchHorFirma property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCFEFchHorFirma(XMLGregorianCalendar value) {
                this.cfeFchHorFirma = value;
            }

            /**
             * Gets the value of the cfecaeId property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getCFECAEId() {
                return cfecaeId;
            }

            /**
             * Sets the value of the cfecaeId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setCFECAEId(Long value) {
                this.cfecaeId = value;
            }

            /**
             * Gets the value of the cfecaeNroIni property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCFECAENroIni() {
                return cfecaeNroIni;
            }

            /**
             * Sets the value of the cfecaeNroIni property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCFECAENroIni(BigInteger value) {
                this.cfecaeNroIni = value;
            }

            /**
             * Gets the value of the cfecaeNroFin property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCFECAENroFin() {
                return cfecaeNroFin;
            }

            /**
             * Sets the value of the cfecaeNroFin property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCFECAENroFin(BigInteger value) {
                this.cfecaeNroFin = value;
            }

            /**
             * Gets the value of the cfecaeFchVenc property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCFECAEFchVenc() {
                return cfecaeFchVenc;
            }

            /**
             * Sets the value of the cfecaeFchVenc property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCFECAEFchVenc(XMLGregorianCalendar value) {
                this.cfecaeFchVenc = value;
            }

            /**
             * Gets the value of the cferutEmisor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCFERUTEmisor() {
                return cferutEmisor;
            }

            /**
             * Sets the value of the cferutEmisor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCFERUTEmisor(String value) {
                this.cferutEmisor = value;
            }

            /**
             * Gets the value of the cfeTotMntPagar property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getCFETotMntPagar() {
                return cfeTotMntPagar;
            }

            /**
             * Sets the value of the cfeTotMntPagar property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setCFETotMntPagar(BigDecimal value) {
                this.cfeTotMntPagar = value;
            }

            /**
             * Gets the value of the numResAutorizadora property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumResAutorizadora() {
                return numResAutorizadora;
            }

            /**
             * Sets the value of the numResAutorizadora property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumResAutorizadora(BigInteger value) {
                this.numResAutorizadora = value;
            }

            /**
             * Gets the value of the anoResAutorizadora property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAnoResAutorizadora() {
                return anoResAutorizadora;
            }

            /**
             * Sets the value of the anoResAutorizadora property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAnoResAutorizadora(BigInteger value) {
                this.anoResAutorizadora = value;
            }

            /**
             * Gets the value of the direccionInvoiCyWeb property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDireccionInvoiCyWeb() {
                return direccionInvoiCyWeb;
            }

            /**
             * Sets the value of the direccionInvoiCyWeb property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDireccionInvoiCyWeb(String value) {
                this.direccionInvoiCyWeb = value;
            }

            /**
             * Gets the value of the codBarRedPagPrimera property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodBarRedPagPrimera() {
                return codBarRedPagPrimera;
            }

            /**
             * Sets the value of the codBarRedPagPrimera property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodBarRedPagPrimera(String value) {
                this.codBarRedPagPrimera = value;
            }

            /**
             * Gets the value of the codBarRedPagSegunda property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodBarRedPagSegunda() {
                return codBarRedPagSegunda;
            }

            /**
             * Sets the value of the codBarRedPagSegunda property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodBarRedPagSegunda(String value) {
                this.codBarRedPagSegunda = value;
            }

            /**
             * Gets the value of the codBarAbtPrimera property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodBarAbtPrimera() {
                return codBarAbtPrimera;
            }

            /**
             * Sets the value of the codBarAbtPrimera property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodBarAbtPrimera(String value) {
                this.codBarAbtPrimera = value;
            }

            /**
             * Gets the value of the codBarAbtSegunda property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodBarAbtSegunda() {
                return codBarAbtSegunda;
            }

            /**
             * Sets the value of the codBarAbtSegunda property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodBarAbtSegunda(String value) {
                this.codBarAbtSegunda = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ErrosItem" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CFEErrCod" type="{http://www.invoicy.com.uy/}MsgCodType"/>
         *                   &lt;element name="CFEErrDesc" type="{http://www.invoicy.com.uy/}MsgDscType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "errosItem"
        })
        public static class Erros {

            @XmlElement(name = "ErrosItem")
            protected List<ErrosItem> errosItem;

            /**
             * Gets the value of the errosItem property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the errosItem property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getErrosItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ErrosItem }
             * 
             * 
             */
            public List<ErrosItem> getErrosItem() {
                if (errosItem == null) {
                    errosItem = new ArrayList<ErrosItem>();
                }
                return this.errosItem;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CFEErrCod" type="{http://www.invoicy.com.uy/}MsgCodType"/>
             *         &lt;element name="CFEErrDesc" type="{http://www.invoicy.com.uy/}MsgDscType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cfeErrCod",
                "cfeErrDesc"
            })
            public static class ErrosItem {

                @XmlElement(name = "CFEErrCod")
                protected int cfeErrCod;
                @XmlElement(name = "CFEErrDesc", required = true)
                protected String cfeErrDesc;

                /**
                 * Gets the value of the cfeErrCod property.
                 * 
                 */
                public int getCFEErrCod() {
                    return cfeErrCod;
                }

                /**
                 * Sets the value of the cfeErrCod property.
                 * 
                 */
                public void setCFEErrCod(int value) {
                    this.cfeErrCod = value;
                }

                /**
                 * Gets the value of the cfeErrDesc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCFEErrDesc() {
                    return cfeErrDesc;
                }

                /**
                 * Sets the value of the cfeErrDesc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCFEErrDesc(String value) {
                    this.cfeErrDesc = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ErrosDGIItem" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CFERetCod">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="3"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="CFERetDesc" type="{http://www.invoicy.com.uy/}MsgDscType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "errosDGIItem"
        })
        public static class ErrosDGI {

            @XmlElement(name = "ErrosDGIItem")
            protected List<ErrosDGIItem> errosDGIItem;

            /**
             * Gets the value of the errosDGIItem property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the errosDGIItem property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getErrosDGIItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ErrosDGIItem }
             * 
             * 
             */
            public List<ErrosDGIItem> getErrosDGIItem() {
                if (errosDGIItem == null) {
                    errosDGIItem = new ArrayList<ErrosDGIItem>();
                }
                return this.errosDGIItem;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CFERetCod">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="3"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="CFERetDesc" type="{http://www.invoicy.com.uy/}MsgDscType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cfeRetCod",
                "cfeRetDesc"
            })
            public static class ErrosDGIItem {

                @XmlElement(name = "CFERetCod", required = true)
                protected String cfeRetCod;
                @XmlElement(name = "CFERetDesc", required = true)
                protected String cfeRetDesc;

                /**
                 * Gets the value of the cfeRetCod property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCFERetCod() {
                    return cfeRetCod;
                }

                /**
                 * Sets the value of the cfeRetCod property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCFERetCod(String value) {
                    this.cfeRetCod = value;
                }

                /**
                 * Gets the value of the cfeRetDesc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCFERetDesc() {
                    return cfeRetDesc;
                }

                /**
                 * Sets the value of the cfeRetDesc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCFERetDesc(String value) {
                    this.cfeRetDesc = value;
                }

            }

        }

    }

}
