//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 05:47:04 PM UYT 
//


package dto.migrate;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openup.cfe.provider.migrate.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openup.cfe.provider.migrate.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RechazoSobreType }
     * 
     */
    public RechazoSobreType createRechazoSobreType() {
        return new RechazoSobreType();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Detalle.Item.CodItem }
     * 
     */
    public CFEInvoiCyType.Detalle.Item.CodItem createCFEInvoiCyTypeDetalleItemCodItem() {
        return new CFEInvoiCyType.Detalle.Item.CodItem();
    }

    /**
     * Create an instance of {@link EncabezadoEnvioType }
     * 
     */
    public EncabezadoEnvioType createEncabezadoEnvioType() {
        return new EncabezadoEnvioType();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.MediosPago }
     * 
     */
    public CFEInvoiCyType.MediosPago createCFEInvoiCyTypeMediosPago() {
        return new CFEInvoiCyType.MediosPago();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.CodBarras.CodBarAbitab }
     * 
     */
    public CFEInvoiCyType.CodBarras.CodBarAbitab createCFEInvoiCyTypeCodBarrasCodBarAbitab() {
        return new CFEInvoiCyType.CodBarras.CodBarAbitab();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Totales.RetencPercepTot.RetencPercepTotItem }
     * 
     */
    public CFEInvoiCyType.Totales.RetencPercepTot.RetencPercepTotItem createCFEInvoiCyTypeTotalesRetencPercepTotRetencPercepTotItem() {
        return new CFEInvoiCyType.Totales.RetencPercepTot.RetencPercepTotItem();
    }

    /**
     * Create an instance of {@link RechazoCFEPartesType }
     * 
     */
    public RechazoCFEPartesType createRechazoCFEPartesType() {
        return new RechazoCFEPartesType();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Detalle }
     * 
     */
    public CFEInvoiCyType.Detalle createCFEInvoiCyTypeDetalle() {
        return new CFEInvoiCyType.Detalle();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Referencia.ReferenciaItem }
     * 
     */
    public CFEInvoiCyType.Referencia.ReferenciaItem createCFEInvoiCyTypeReferenciaReferenciaItem() {
        return new CFEInvoiCyType.Referencia.ReferenciaItem();
    }

    /**
     * Create an instance of {@link ListaCFERetornoType.CFE.ErrosDGI.ErrosDGIItem }
     * 
     */
    public ListaCFERetornoType.CFE.ErrosDGI.ErrosDGIItem createListaCFERetornoTypeCFEErrosDGIErrosDGIItem() {
        return new ListaCFERetornoType.CFE.ErrosDGI.ErrosDGIItem();
    }

    /**
     * Create an instance of {@link CFEInvoiCyCollectionType }
     * 
     */
    public CFEInvoiCyCollectionType createCFEInvoiCyCollectionType() {
        return new CFEInvoiCyCollectionType();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.SubTotInfo.STIItem }
     * 
     */
    public CFEInvoiCyType.SubTotInfo.STIItem createCFEInvoiCyTypeSubTotInfoSTIItem() {
        return new CFEInvoiCyType.SubTotInfo.STIItem();
    }

    /**
     * Create an instance of {@link ListaCFERetornoType.CFE }
     * 
     */
    public ListaCFERetornoType.CFE createListaCFERetornoTypeCFE() {
        return new ListaCFERetornoType.CFE();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Detalle.Item.RetencPercep.RetencPercepItem }
     * 
     */
    public CFEInvoiCyType.Detalle.Item.RetencPercep.RetencPercepItem createCFEInvoiCyTypeDetalleItemRetencPercepRetencPercepItem() {
        return new CFEInvoiCyType.Detalle.Item.RetencPercep.RetencPercepItem();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Detalle.Item.SubDescuento }
     * 
     */
    public CFEInvoiCyType.Detalle.Item.SubDescuento createCFEInvoiCyTypeDetalleItemSubDescuento() {
        return new CFEInvoiCyType.Detalle.Item.SubDescuento();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.IdDoc }
     * 
     */
    public CFEInvoiCyType.IdDoc createCFEInvoiCyTypeIdDoc() {
        return new CFEInvoiCyType.IdDoc();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Detalle.Item.RetencPercep }
     * 
     */
    public CFEInvoiCyType.Detalle.Item.RetencPercep createCFEInvoiCyTypeDetalleItemRetencPercep() {
        return new CFEInvoiCyType.Detalle.Item.RetencPercep();
    }

    /**
     * Create an instance of {@link ListaCFERetornoType }
     * 
     */
    public ListaCFERetornoType createListaCFERetornoType() {
        return new ListaCFERetornoType();
    }

    /**
     * Create an instance of {@link RechazoCFEDGIType }
     * 
     */
    public RechazoCFEDGIType createRechazoCFEDGIType() {
        return new RechazoCFEDGIType();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType }
     * 
     */
    public CFEInvoiCyType createCFEInvoiCyType() {
        return new CFEInvoiCyType();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Detalle.Item.SubDescuento.SubDescuentoItem }
     * 
     */
    public CFEInvoiCyType.Detalle.Item.SubDescuento.SubDescuentoItem createCFEInvoiCyTypeDetalleItemSubDescuentoSubDescuentoItem() {
        return new CFEInvoiCyType.Detalle.Item.SubDescuento.SubDescuentoItem();
    }

    /**
     * Create an instance of {@link ListaCFERetornoType.CFE.ErrosDGI }
     * 
     */
    public ListaCFERetornoType.CFE.ErrosDGI createListaCFERetornoTypeCFEErrosDGI() {
        return new ListaCFERetornoType.CFE.ErrosDGI();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.DscRcgGlobal }
     * 
     */
    public CFEInvoiCyType.DscRcgGlobal createCFEInvoiCyTypeDscRcgGlobal() {
        return new CFEInvoiCyType.DscRcgGlobal();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Receptor }
     * 
     */
    public CFEInvoiCyType.Receptor createCFEInvoiCyTypeReceptor() {
        return new CFEInvoiCyType.Receptor();
    }

    /**
     * Create an instance of {@link InfoRespOriType }
     * 
     */
    public InfoRespOriType createInfoRespOriType() {
        return new InfoRespOriType();
    }

    /**
     * Create an instance of {@link ObsCFCType }
     * 
     */
    public ObsCFCType createObsCFCType() {
        return new ObsCFCType();
    }

    /**
     * Create an instance of {@link ListaCFERetornoType.CFE.Erros }
     * 
     */
    public ListaCFERetornoType.CFE.Erros createListaCFERetornoTypeCFEErros() {
        return new ListaCFERetornoType.CFE.Erros();
    }

    /**
     * Create an instance of {@link MotivosRechazoType }
     * 
     */
    public MotivosRechazoType createMotivosRechazoType() {
        return new MotivosRechazoType();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.DscRcgGlobal.DRGItem }
     * 
     */
    public CFEInvoiCyType.DscRcgGlobal.DRGItem createCFEInvoiCyTypeDscRcgGlobalDRGItem() {
        return new CFEInvoiCyType.DscRcgGlobal.DRGItem();
    }

    /**
     * Create an instance of {@link EncabezadoRetornoType }
     * 
     */
    public EncabezadoRetornoType createEncabezadoRetornoType() {
        return new EncabezadoRetornoType();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.CodBarras }
     * 
     */
    public CFEInvoiCyType.CodBarras createCFEInvoiCyTypeCodBarras() {
        return new CFEInvoiCyType.CodBarras();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.CodBarras.CodBarRedPagos }
     * 
     */
    public CFEInvoiCyType.CodBarras.CodBarRedPagos createCFEInvoiCyTypeCodBarrasCodBarRedPagos() {
        return new CFEInvoiCyType.CodBarras.CodBarRedPagos();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.SubTotInfo }
     * 
     */
    public CFEInvoiCyType.SubTotInfo createCFEInvoiCyTypeSubTotInfo() {
        return new CFEInvoiCyType.SubTotInfo();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.MediosPago.MediosPagoItem }
     * 
     */
    public CFEInvoiCyType.MediosPago.MediosPagoItem createCFEInvoiCyTypeMediosPagoMediosPagoItem() {
        return new CFEInvoiCyType.MediosPago.MediosPagoItem();
    }

    /**
     * Create an instance of {@link MotivosRechazoType.Motivo }
     * 
     */
    public MotivosRechazoType.Motivo createMotivosRechazoTypeMotivo() {
        return new MotivosRechazoType.Motivo();
    }

    /**
     * Create an instance of {@link ListaCFERetornoType.CFE.Erros.ErrosItem }
     * 
     */
    public ListaCFERetornoType.CFE.Erros.ErrosItem createListaCFERetornoTypeCFEErrosErrosItem() {
        return new ListaCFERetornoType.CFE.Erros.ErrosItem();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Emisor }
     * 
     */
    public CFEInvoiCyType.Emisor createCFEInvoiCyTypeEmisor() {
        return new CFEInvoiCyType.Emisor();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Totales }
     * 
     */
    public CFEInvoiCyType.Totales createCFEInvoiCyTypeTotales() {
        return new CFEInvoiCyType.Totales();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Referencia }
     * 
     */
    public CFEInvoiCyType.Referencia createCFEInvoiCyTypeReferencia() {
        return new CFEInvoiCyType.Referencia();
    }

    /**
     * Create an instance of {@link ListaCFERetornoType.CFE.CFEDatosAvanzados }
     * 
     */
    public ListaCFERetornoType.CFE.CFEDatosAvanzados createListaCFERetornoTypeCFECFEDatosAvanzados() {
        return new ListaCFERetornoType.CFE.CFEDatosAvanzados();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Mandante }
     * 
     */
    public CFEInvoiCyType.Mandante createCFEInvoiCyTypeMandante() {
        return new CFEInvoiCyType.Mandante();
    }

    /**
     * Create an instance of {@link EnvioCFE }
     * 
     */
    public EnvioCFE createEnvioCFE() {
        return new EnvioCFE();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Detalle.Item }
     * 
     */
    public CFEInvoiCyType.Detalle.Item createCFEInvoiCyTypeDetalleItem() {
        return new CFEInvoiCyType.Detalle.Item();
    }

    /**
     * Create an instance of {@link EncabezadoRetornoCFEType }
     * 
     */
    public EncabezadoRetornoCFEType createEncabezadoRetornoCFEType() {
        return new EncabezadoRetornoCFEType();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Detalle.Item.SubRecargo }
     * 
     */
    public CFEInvoiCyType.Detalle.Item.SubRecargo createCFEInvoiCyTypeDetalleItemSubRecargo() {
        return new CFEInvoiCyType.Detalle.Item.SubRecargo();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Detalle.Item.CodItem.CodItemItem }
     * 
     */
    public CFEInvoiCyType.Detalle.Item.CodItem.CodItemItem createCFEInvoiCyTypeDetalleItemCodItemCodItemItem() {
        return new CFEInvoiCyType.Detalle.Item.CodItem.CodItemItem();
    }

    /**
     * Create an instance of {@link RechazoRepType }
     * 
     */
    public RechazoRepType createRechazoRepType() {
        return new RechazoRepType();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Detalle.Item.SubRecargo.SubRecargoItem }
     * 
     */
    public CFEInvoiCyType.Detalle.Item.SubRecargo.SubRecargoItem createCFEInvoiCyTypeDetalleItemSubRecargoSubRecargoItem() {
        return new CFEInvoiCyType.Detalle.Item.SubRecargo.SubRecargoItem();
    }

    /**
     * Create an instance of {@link CFEInvoiCyType.Totales.RetencPercepTot }
     * 
     */
    public CFEInvoiCyType.Totales.RetencPercepTot createCFEInvoiCyTypeTotalesRetencPercepTot() {
        return new CFEInvoiCyType.Totales.RetencPercepTot();
    }

}
