//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.11 at 02:06:34 PM UYT 
//


package uy.gub.dgi.cfe;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for IdDoc_Rem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdDoc_Rem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoCFE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *               &lt;enumeration value="181"/>
 *               &lt;enumeration value="281"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Serie" type="{http://cfe.dgi.gub.uy}SerieType"/>
 *         &lt;element name="Nro" type="{http://cfe.dgi.gub.uy}NroCFEType"/>
 *         &lt;element name="NroInterno" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FchEmis" type="{http://cfe.dgi.gub.uy}FechaType"/>
 *         &lt;element name="TipoTraslado" type="{http://cfe.dgi.gub.uy}TipoTrasladoType"/>
 *         &lt;element name="IndPropiedad" type="{http://cfe.dgi.gub.uy}IndPropiedadType" minOccurs="0"/>
 *         &lt;element name="TipoDocProp" type="{http://cfe.dgi.gub.uy}DocType" minOccurs="0"/>
 *         &lt;element name="CodPaisProp" type="{http://cfe.dgi.gub.uy}CodPaisType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="DocProp" type="{http://cfe.dgi.gub.uy}NroDocType" minOccurs="0"/>
 *           &lt;element name="DocPropExt" minOccurs="0">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;maxLength value="20"/>
 *                 &lt;whiteSpace value="collapse"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="RznSocProp" type="{http://cfe.dgi.gub.uy}RznSocType" minOccurs="0"/>
 *         &lt;element name="InfoAdicionalDoc" type="{http://cfe.dgi.gub.uy}InfoAdicionalType" minOccurs="0"/>
 *         &lt;element name="SecProf" type="{http://cfe.dgi.gub.uy}SecProfType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdDoc_Rem", propOrder = {
    "tipoCFE",
    "serie",
    "nro",
    "nroInterno",
    "fchEmis",
    "tipoTraslado",
    "indPropiedad",
    "tipoDocProp",
    "codPaisProp",
    "docProp",
    "docPropExt",
    "rznSocProp",
    "infoAdicionalDoc",
    "secProf"
})
public class IdDocRem {

    @XmlElement(name = "TipoCFE", required = true)
    protected BigInteger tipoCFE;
    @XmlElement(name = "Serie", required = true)
    protected String serie;
    @XmlElement(name = "Nro", required = true)
    protected BigInteger nro;
    @XmlElement(name = "NroInterno")
    protected String nroInterno;
    @XmlElement(name = "FchEmis", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fchEmis;
    @XmlElement(name = "TipoTraslado", required = true)
    protected BigInteger tipoTraslado;
    @XmlElement(name = "IndPropiedad")
    protected BigInteger indPropiedad;
    @XmlElement(name = "TipoDocProp")
    @XmlSchemaType(name = "positiveInteger")
    protected Integer tipoDocProp;
    @XmlElement(name = "CodPaisProp")
    protected String codPaisProp;
    @XmlElement(name = "DocProp")
    protected String docProp;
    @XmlElement(name = "DocPropExt")
    protected String docPropExt;
    @XmlElement(name = "RznSocProp")
    protected String rznSocProp;
    @XmlElement(name = "InfoAdicionalDoc")
    protected String infoAdicionalDoc;
    @XmlElement(name = "SecProf")
    protected BigInteger secProf;

    /**
     * Gets the value of the tipoCFE property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTipoCFE() {
        return tipoCFE;
    }

    /**
     * Sets the value of the tipoCFE property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTipoCFE(BigInteger value) {
        this.tipoCFE = value;
    }

    /**
     * Gets the value of the serie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerie() {
        return serie;
    }

    /**
     * Sets the value of the serie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerie(String value) {
        this.serie = value;
    }

    /**
     * Gets the value of the nro property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNro() {
        return nro;
    }

    /**
     * Sets the value of the nro property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNro(BigInteger value) {
        this.nro = value;
    }

    /**
     * Gets the value of the nroInterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNroInterno() {
        return nroInterno;
    }

    /**
     * Sets the value of the nroInterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNroInterno(String value) {
        this.nroInterno = value;
    }

    /**
     * Gets the value of the fchEmis property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFchEmis() {
        return fchEmis;
    }

    /**
     * Sets the value of the fchEmis property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFchEmis(XMLGregorianCalendar value) {
        this.fchEmis = value;
    }

    /**
     * Gets the value of the tipoTraslado property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTipoTraslado() {
        return tipoTraslado;
    }

    /**
     * Sets the value of the tipoTraslado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTipoTraslado(BigInteger value) {
        this.tipoTraslado = value;
    }

    /**
     * Gets the value of the indPropiedad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndPropiedad() {
        return indPropiedad;
    }

    /**
     * Sets the value of the indPropiedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndPropiedad(BigInteger value) {
        this.indPropiedad = value;
    }

    /**
     * Gets the value of the tipoDocProp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTipoDocProp() {
        return tipoDocProp;
    }

    /**
     * Sets the value of the tipoDocProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTipoDocProp(Integer value) {
        this.tipoDocProp = value;
    }

    /**
     * Gets the value of the codPaisProp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodPaisProp() {
        return codPaisProp;
    }

    /**
     * Sets the value of the codPaisProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodPaisProp(String value) {
        this.codPaisProp = value;
    }

    /**
     * Gets the value of the docProp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocProp() {
        return docProp;
    }

    /**
     * Sets the value of the docProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocProp(String value) {
        this.docProp = value;
    }

    /**
     * Gets the value of the docPropExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocPropExt() {
        return docPropExt;
    }

    /**
     * Sets the value of the docPropExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocPropExt(String value) {
        this.docPropExt = value;
    }

    /**
     * Gets the value of the rznSocProp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRznSocProp() {
        return rznSocProp;
    }

    /**
     * Sets the value of the rznSocProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRznSocProp(String value) {
        this.rznSocProp = value;
    }

    /**
     * Gets the value of the infoAdicionalDoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfoAdicionalDoc() {
        return infoAdicionalDoc;
    }

    /**
     * Sets the value of the infoAdicionalDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfoAdicionalDoc(String value) {
        this.infoAdicionalDoc = value;
    }

    /**
     * Gets the value of the secProf property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSecProf() {
        return secProf;
    }

    /**
     * Sets the value of the secProf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSecProf(BigInteger value) {
        this.secProf = value;
    }

}
