//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 11:51:12 AM UYT 
//


package com.uruware.ucfe.inbox.webservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.uruware.ucfe.inbox.webservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequerimientoParaUcfe_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "RequerimientoParaUcfe");
    private final static QName _ReqBody_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "ReqBody");
    private final static QName _RequerimientoParaUcfeEmailEnvioPdfReceptor_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "EmailEnvioPdfReceptor");
    private final static QName _RequerimientoParaUcfeCodComercio_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "CodComercio");
    private final static QName _RequerimientoParaUcfeEstadoSituacion_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "EstadoSituacion");
    private final static QName _RequerimientoParaUcfeImpresora_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "Impresora");
    private final static QName _RequerimientoParaUcfeFechaReq_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "FechaReq");
    private final static QName _RequerimientoParaUcfeSerie_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "Serie");
    private final static QName _RequerimientoParaUcfeNumeroCfe_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "NumeroCfe");
    private final static QName _RequerimientoParaUcfeCodRta_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "CodRta");
    private final static QName _RequerimientoParaUcfeDatosQr_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "DatosQr");
    private final static QName _RequerimientoParaUcfeTipoCfe_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "TipoCfe");
    private final static QName _RequerimientoParaUcfeCertificado_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "Certificado");
    private final static QName _RequerimientoParaUcfeHoraReq_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "HoraReq");
    private final static QName _RequerimientoParaUcfeCfeXmlOTexto_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "CfeXmlOTexto");
    private final static QName _RequerimientoParaUcfeCodTerminal_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "CodTerminal");
    private final static QName _RequerimientoParaUcfeCifrarComplementoFiscal_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "CifrarComplementoFiscal");
    private final static QName _RequerimientoParaUcfeAdenda_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "Adenda");
    private final static QName _RequerimientoParaUcfeRechCom_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "RechCom");
    private final static QName _RequerimientoParaUcfeUuid_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "Uuid");
    private final static QName _RequerimientoParaUcfeIdReq_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "IdReq");
    private final static QName _RequerimientoParaUcfeRutEmisor_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "RutEmisor");
    private final static QName _ReqBodyReq_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "Req");
    private final static QName _ReqBodyReqEnc_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "ReqEnc");
    private final static QName _ReqBodyHMAC_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "HMAC");
    private final static QName _ReqBodyRequestDate_QNAME = new QName("http://www.uruware.com/ucfe/inbox/webservice", "RequestDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.uruware.ucfe.inbox.webservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReqBody }
     * 
     */
    public ReqBody createReqBody() {
        return new ReqBody();
    }

    /**
     * Create an instance of {@link RequerimientoParaUcfe }
     * 
     */
    public RequerimientoParaUcfe createRequerimientoParaUcfe() {
        return new RequerimientoParaUcfe();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequerimientoParaUcfe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "RequerimientoParaUcfe")
    public JAXBElement<RequerimientoParaUcfe> createRequerimientoParaUcfe(RequerimientoParaUcfe value) {
        return new JAXBElement<RequerimientoParaUcfe>(_RequerimientoParaUcfe_QNAME, RequerimientoParaUcfe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReqBody }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "ReqBody")
    public JAXBElement<ReqBody> createReqBody(ReqBody value) {
        return new JAXBElement<ReqBody>(_ReqBody_QNAME, ReqBody.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "EmailEnvioPdfReceptor", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeEmailEnvioPdfReceptor(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeEmailEnvioPdfReceptor_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "CodComercio", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeCodComercio(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeCodComercio_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "EstadoSituacion", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeEstadoSituacion(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeEstadoSituacion_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "Impresora", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeImpresora(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeImpresora_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "FechaReq", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeFechaReq(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeFechaReq_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "Serie", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeSerie(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeSerie_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "NumeroCfe", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeNumeroCfe(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeNumeroCfe_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "CodRta", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeCodRta(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeCodRta_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "DatosQr", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeDatosQr(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeDatosQr_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "TipoCfe", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeTipoCfe(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeTipoCfe_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "Certificado", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeCertificado(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeCertificado_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "HoraReq", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeHoraReq(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeHoraReq_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "CfeXmlOTexto", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeCfeXmlOTexto(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeCfeXmlOTexto_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "CodTerminal", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeCodTerminal(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeCodTerminal_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "CifrarComplementoFiscal", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeCifrarComplementoFiscal(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeCifrarComplementoFiscal_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "Adenda", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeAdenda(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeAdenda_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "RechCom", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeRechCom(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeRechCom_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "Uuid", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeUuid(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeUuid_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "IdReq", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeIdReq(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeIdReq_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "RutEmisor", scope = RequerimientoParaUcfe.class)
    public JAXBElement<String> createRequerimientoParaUcfeRutEmisor(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeRutEmisor_QNAME, String.class, RequerimientoParaUcfe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequerimientoParaUcfe }{@code >}}
     * 
     */
    /*
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "Req", scope = ReqBody.class)
    public JAXBElement<RequerimientoParaUcfe> createReqBodyReq(RequerimientoParaUcfe value) {
        return new JAXBElement<RequerimientoParaUcfe>(_ReqBodyReq_QNAME, RequerimientoParaUcfe.class, ReqBody.class, value);
    }
     */

    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "Req", scope = ReqBody.class)
    public JAXBElement<String> createReqBodyReq(String value) {
        return new JAXBElement<String>(_ReqBodyReq_QNAME, String.class, ReqBody.class, value);
    }



    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "ReqEnc", scope = ReqBody.class)
    public JAXBElement<String> createReqBodyReqEnc(String value) {
        return new JAXBElement<String>(_ReqBodyReqEnc_QNAME, String.class, ReqBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "HMAC", scope = ReqBody.class)
    public JAXBElement<String> createReqBodyHMAC(String value) {
        return new JAXBElement<String>(_ReqBodyHMAC_QNAME, String.class, ReqBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "CodComercio", scope = ReqBody.class)
    public JAXBElement<String> createReqBodyCodComercio(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeCodComercio_QNAME, String.class, ReqBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "CodTerminal", scope = ReqBody.class)
    public JAXBElement<String> createReqBodyCodTerminal(String value) {
        return new JAXBElement<String>(_RequerimientoParaUcfeCodTerminal_QNAME, String.class, ReqBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uruware.com/ucfe/inbox/webservice", name = "RequestDate", scope = ReqBody.class)
    public JAXBElement<String> createReqBodyRequestDate(String value) {
        return new JAXBElement<String>(_ReqBodyRequestDate_QNAME, String.class, ReqBody.class, value);
    }

}
