//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 11:51:12 AM UYT 
//


package com.uruware.ucfe.inbox.webservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ReqBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReqBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HMAC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Req" type="{http://www.uruware.com/ucfe/inbox/webservice}RequerimientoParaUcfe" minOccurs="0"/>
 *         &lt;element name="RequestDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ReqEnc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodComercio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodTerminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReqBody", propOrder = {
    "hmac",
    "req",
    "requestDate",
    "tout",
    "reqEnc",
    "codComercio",
    "codTerminal"
})
@XmlRootElement
public class ReqBody {

    @XmlElementRef(name = "HMAC", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String hmac;

    /*
    @XmlElementRef(name = "Req", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = JAXBElement.class, required = false)
    protected JAXBElement<RequerimientoParaUcfe> req;
     */

    @XmlElementRef(name = "Req", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String req;


    @XmlElementRef(name = "RequestDate", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String requestDate;
    @XmlElement(name = "Tout")
    protected Integer tout;
    @XmlElementRef(name = "ReqEnc", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String reqEnc;
    @XmlElementRef(name = "CodComercio", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String codComercio;
    @XmlElementRef(name = "CodTerminal", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String codTerminal;

    /**
     * Gets the value of the hmac property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getHMAC() {
        return hmac;
    }

    /**
     * Sets the value of the hmac property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHMAC(String value) {
        this.hmac = value;
    }

    /**
     * Gets the value of the req property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RequerimientoParaUcfe }{@code >}
     *     
     */
    public String getReq() {
        //public JAXBElement<RequerimientoParaUcfe> getReq() {
        return req;
    }

    /**
     * Sets the value of the req property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RequerimientoParaUcfe }{@code >}
     *     
     */
    public void setReq(String value) {
        //public void setReq(JAXBElement<RequerimientoParaUcfe> value) {
        this.req = value;
    }

    /**
     * Gets the value of the requestDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getRequestDate() {
        return requestDate;
    }

    /**
     * Sets the value of the requestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRequestDate(String value) {
        this.requestDate = value;
    }

    /**
     * Gets the value of the tout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTout() {
        return tout;
    }

    /**
     * Sets the value of the tout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTout(Integer value) {
        this.tout = value;
    }

    /**
     * Gets the value of the reqEnc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getReqEnc() {
        return reqEnc;
    }

    /**
     * Sets the value of the reqEnc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReqEnc(String value) {
        this.reqEnc = value;
    }

    /**
     * Gets the value of the codComercio property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getCodComercio() {
        return codComercio;
    }

    /**
     * Sets the value of the codComercio property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodComercio(String value) {
        this.codComercio = value;
    }

    /**
     * Gets the value of the codTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getCodTerminal() {
        return codTerminal;
    }

    /**
     * Sets the value of the codTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodTerminal(String value) {
        this.codTerminal = value;
    }

}
