//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 11:51:12 AM UYT 
//


package com.uruware.ucfe.inbox.webservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequerimientoParaUcfe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequerimientoParaUcfe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Adenda" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Certificado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CfeXmlOTexto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CifrarComplementoFiscal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodComercio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodRta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodTerminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DatosQr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmailEnvioPdfReceptor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EstadoSituacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FechaReq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HoraReq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IdReq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Impresora" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumeroCfe" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RechCom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RutEmisor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Serie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TipoCfe" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TipoMensaje" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Uuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequerimientoParaUcfe", propOrder = {
    "adenda",
    "certificado",
    "cfeXmlOTexto",
    "cifrarComplementoFiscal",
    "codComercio",
    "codRta",
    "codTerminal",
    "datosQr",
    "emailEnvioPdfReceptor",
    "estadoSituacion",
    "fechaReq",
    "horaReq",
    "idReq",
    "impresora",
    "numeroCfe",
    "rechCom",
    "rutEmisor",
    "serie",
    "tipoCfe",
    "tipoMensaje",
    "uuid"
})
public class RequerimientoParaUcfe {

    @XmlElementRef(name = "Adenda", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String adenda;
    @XmlElementRef(name = "Certificado", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String certificado;
    @XmlElementRef(name = "CfeXmlOTexto", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String cfeXmlOTexto;
    @XmlElementRef(name = "CifrarComplementoFiscal", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String cifrarComplementoFiscal;
    @XmlElementRef(name = "CodComercio", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String codComercio;
    @XmlElementRef(name = "CodRta", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String codRta;
    @XmlElementRef(name = "CodTerminal", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String codTerminal;
    @XmlElementRef(name = "DatosQr", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String datosQr;
    @XmlElementRef(name = "EmailEnvioPdfReceptor", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String emailEnvioPdfReceptor;
    @XmlElementRef(name = "EstadoSituacion", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String estadoSituacion;
    @XmlElementRef(name = "FechaReq", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String fechaReq;
    @XmlElementRef(name = "HoraReq", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String horaReq;
    @XmlElementRef(name = "IdReq", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String idReq;
    @XmlElementRef(name = "Impresora", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String impresora;
    @XmlElementRef(name = "NumeroCfe", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String numeroCfe;
    @XmlElementRef(name = "RechCom", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String rechCom;
    @XmlElementRef(name = "RutEmisor", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String rutEmisor;
    @XmlElementRef(name = "Serie", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String serie;
    @XmlElementRef(name = "TipoCfe", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String tipoCfe;
    @XmlElement(name = "TipoMensaje")
    protected Integer tipoMensaje;
    @XmlElementRef(name = "Uuid", namespace = "http://www.uruware.com/ucfe/inbox/webservice", type = String.class, required = false)
    protected String uuid;

    /**
     * Gets the value of the adenda property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getAdenda() {
        return adenda;
    }

    /**
     * Sets the value of the adenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAdenda(String value) {
        this.adenda = value;
    }

    /**
     * Gets the value of the certificado property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getCertificado() {
        return certificado;
    }

    /**
     * Sets the value of the certificado property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCertificado(String value) {
        this.certificado = value;
    }

    /**
     * Gets the value of the cfeXmlOTexto property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getCfeXmlOTexto() {
        return cfeXmlOTexto;
    }

    /**
     * Sets the value of the cfeXmlOTexto property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCfeXmlOTexto(String value) {
        this.cfeXmlOTexto = value;
    }

    /**
     * Gets the value of the cifrarComplementoFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getCifrarComplementoFiscal() {
        return cifrarComplementoFiscal;
    }

    /**
     * Sets the value of the cifrarComplementoFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCifrarComplementoFiscal(String value) {
        this.cifrarComplementoFiscal = value;
    }

    /**
     * Gets the value of the codComercio property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getCodComercio() {
        return codComercio;
    }

    /**
     * Sets the value of the codComercio property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodComercio(String value) {
        this.codComercio = value;
    }

    /**
     * Gets the value of the codRta property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getCodRta() {
        return codRta;
    }

    /**
     * Sets the value of the codRta property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodRta(String value) {
        this.codRta = value;
    }

    /**
     * Gets the value of the codTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getCodTerminal() {
        return codTerminal;
    }

    /**
     * Sets the value of the codTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodTerminal(String value) {
        this.codTerminal = value;
    }

    /**
     * Gets the value of the datosQr property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getDatosQr() {
        return datosQr;
    }

    /**
     * Sets the value of the datosQr property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDatosQr(String value) {
        this.datosQr = value;
    }

    /**
     * Gets the value of the emailEnvioPdfReceptor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getEmailEnvioPdfReceptor() {
        return emailEnvioPdfReceptor;
    }

    /**
     * Sets the value of the emailEnvioPdfReceptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEmailEnvioPdfReceptor(String value) {
        this.emailEnvioPdfReceptor = value;
    }

    /**
     * Gets the value of the estadoSituacion property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getEstadoSituacion() {
        return estadoSituacion;
    }

    /**
     * Sets the value of the estadoSituacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEstadoSituacion(String value) {
        this.estadoSituacion = value;
    }

    /**
     * Gets the value of the fechaReq property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getFechaReq() {
        return fechaReq;
    }

    /**
     * Sets the value of the fechaReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFechaReq(String value) {
        this.fechaReq = value;
    }

    /**
     * Gets the value of the horaReq property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getHoraReq() {
        return horaReq;
    }

    /**
     * Sets the value of the horaReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHoraReq(String value) {
        this.horaReq = value;
    }

    /**
     * Gets the value of the idReq property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getIdReq() {
        return idReq;
    }

    /**
     * Sets the value of the idReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIdReq(String value) {
        this.idReq = value;
    }

    /**
     * Gets the value of the impresora property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getImpresora() {
        return impresora;
    }

    /**
     * Sets the value of the impresora property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setImpresora(String value) {
        this.impresora = value;
    }

    /**
     * Gets the value of the numeroCfe property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getNumeroCfe() {
        return numeroCfe;
    }

    /**
     * Sets the value of the numeroCfe property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNumeroCfe(String value) {
        this.numeroCfe = value;
    }

    /**
     * Gets the value of the rechCom property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getRechCom() {
        return rechCom;
    }

    /**
     * Sets the value of the rechCom property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRechCom(String value) {
        this.rechCom = value;
    }

    /**
     * Gets the value of the rutEmisor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getRutEmisor() {
        return rutEmisor;
    }

    /**
     * Sets the value of the rutEmisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRutEmisor(String value) {
        this.rutEmisor = value;
    }

    /**
     * Gets the value of the serie property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getSerie() {
        return serie;
    }

    /**
     * Sets the value of the serie property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSerie(String value) {
        this.serie = value;
    }

    /**
     * Gets the value of the tipoCfe property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getTipoCfe() {
        return tipoCfe;
    }

    /**
     * Sets the value of the tipoCfe property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTipoCfe(String value) {
        this.tipoCfe = value;
    }

    /**
     * Gets the value of the tipoMensaje property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTipoMensaje() {
        return tipoMensaje;
    }

    /**
     * Sets the value of the tipoMensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTipoMensaje(Integer value) {
        this.tipoMensaje = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

}
