//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.11 at 02:07:01 PM UYT 
//


package dto.sisteco.cfe;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Montos_Bol complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Montos_Bol">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Mnts_Bol_Item" maxOccurs="1000">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Fecha" type="{http://cfe.dgi.gub.uy}FechaType"/>
 *                   &lt;element name="CodSuc" type="{http://cfe.dgi.gub.uy}CodSucType"/>
 *                   &lt;element name="TotMntNoGrv" type="{http://cfe.dgi.gub.uy}MontoType" minOccurs="0"/>
 *                   &lt;element name="TotMntIVAenSusp" type="{http://cfe.dgi.gub.uy}MontoType" minOccurs="0"/>
 *                   &lt;element name="TotMntTotal" type="{http://cfe.dgi.gub.uy}MontoType"/>
 *                   &lt;element name="TotMntRetenido" type="{http://cfe.dgi.gub.uy}Monto_admite_negType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Montos_Bol", propOrder = {
    "mntsBolItem"
})
public class MontosBol {

    @XmlElement(name = "Mnts_Bol_Item", required = true)
    protected List<MntsBolItem> mntsBolItem;

    /**
     * Gets the value of the mntsBolItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mntsBolItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMntsBolItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MntsBolItem }
     * 
     * 
     */
    public List<MntsBolItem> getMntsBolItem() {
        if (mntsBolItem == null) {
            mntsBolItem = new ArrayList<MntsBolItem>();
        }
        return this.mntsBolItem;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Fecha" type="{http://cfe.dgi.gub.uy}FechaType"/>
     *         &lt;element name="CodSuc" type="{http://cfe.dgi.gub.uy}CodSucType"/>
     *         &lt;element name="TotMntNoGrv" type="{http://cfe.dgi.gub.uy}MontoType" minOccurs="0"/>
     *         &lt;element name="TotMntIVAenSusp" type="{http://cfe.dgi.gub.uy}MontoType" minOccurs="0"/>
     *         &lt;element name="TotMntTotal" type="{http://cfe.dgi.gub.uy}MontoType"/>
     *         &lt;element name="TotMntRetenido" type="{http://cfe.dgi.gub.uy}Monto_admite_negType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fecha",
        "codSuc",
        "totMntNoGrv",
        "totMntIVAenSusp",
        "totMntTotal",
        "totMntRetenido"
    })
    public static class MntsBolItem {

        @XmlElement(name = "Fecha", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fecha;
        @XmlElement(name = "CodSuc", required = true)
        protected BigInteger codSuc;
        @XmlElement(name = "TotMntNoGrv")
        protected BigDecimal totMntNoGrv;
        @XmlElement(name = "TotMntIVAenSusp")
        protected BigDecimal totMntIVAenSusp;
        @XmlElement(name = "TotMntTotal", required = true)
        protected BigDecimal totMntTotal;
        @XmlElement(name = "TotMntRetenido")
        protected BigDecimal totMntRetenido;

        /**
         * Gets the value of the fecha property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFecha(XMLGregorianCalendar value) {
            this.fecha = value;
        }

        /**
         * Gets the value of the codSuc property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCodSuc() {
            return codSuc;
        }

        /**
         * Sets the value of the codSuc property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCodSuc(BigInteger value) {
            this.codSuc = value;
        }

        /**
         * Gets the value of the totMntNoGrv property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotMntNoGrv() {
            return totMntNoGrv;
        }

        /**
         * Sets the value of the totMntNoGrv property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTotMntNoGrv(BigDecimal value) {
            this.totMntNoGrv = value;
        }

        /**
         * Gets the value of the totMntIVAenSusp property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotMntIVAenSusp() {
            return totMntIVAenSusp;
        }

        /**
         * Sets the value of the totMntIVAenSusp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTotMntIVAenSusp(BigDecimal value) {
            this.totMntIVAenSusp = value;
        }

        /**
         * Gets the value of the totMntTotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotMntTotal() {
            return totMntTotal;
        }

        /**
         * Sets the value of the totMntTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTotMntTotal(BigDecimal value) {
            this.totMntTotal = value;
        }

        /**
         * Gets the value of the totMntRetenido property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotMntRetenido() {
            return totMntRetenido;
        }

        /**
         * Sets the value of the totMntRetenido property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTotMntRetenido(BigDecimal value) {
            this.totMntRetenido = value;
        }

    }

}
