//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.11 at 02:07:01 PM UYT 
//


package dto.sisteco.cfe;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for RsmnData_Resg_Cont complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RsmnData_Resg_Cont">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Montos" type="{http://cfe.dgi.gub.uy}Montos_Res" minOccurs="0"/>
 *         &lt;element name="CantCFCEmi" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RsmnData_Resg_Cont", propOrder = {
    "montos",
    "cantCFCEmi"
})
public class RsmnDataResgCont {

    @XmlElement(name = "Montos")
    protected MontosRes montos;
    @XmlElement(name = "CantCFCEmi", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger cantCFCEmi;

    /**
     * Gets the value of the montos property.
     *
     * @return
     *     possible object is
     *     {@link MontosRes }
     *
     */
    public MontosRes getMontos() {
        return montos;
    }

    /**
     * Sets the value of the montos property.
     *
     * @param value
     *     allowed object is
     *     {@link MontosRes }
     *     
     */
    public void setMontos(MontosRes value) {
        this.montos = value;
    }

    /**
     * Gets the value of the cantCFCEmi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCantCFCEmi() {
        return cantCFCEmi;
    }

    /**
     * Sets the value of the cantCFCEmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCantCFCEmi(BigInteger value) {
        this.cantCFCEmi = value;
    }

}
